### ISSUE TITLE
Sirdata undetected on some websites

### ISSUE THREAD

**Issue by Shadok** [MathRobin/Never-Consent#27]
Hello,

Thanks for this extension.
I noticed that clubic.com use SirData consentment platfom but Never-Consent doesn't work on this website (although the platform is supported by the extension - 1.5.1 on my end, with Firefox 75.0 x64 on Windows 10 1909) :
https://www.clubic.com/

Regards.

**Comment by Shadok** [comment]
I am not sure, since i just started to read your code (and it's not my area of expertise) but it seems they use sddanJS instead of sddan, making it a custom implementation, which would explain the situation.

If that's the case, would it be possible to detect the presence of sddan if the externally loaded js files url ?

**Comment by MathRobin** [comment]
I don't know what is sddan, but maybe you're true. Will investigate.

Many many thanks for your feed back and bug report. Will help many other people to protect their privacy

**Comment by Shadok** [comment]
It seems you detect SirData wiht window.sddan in your code.

**Comment by MathRobin** [comment]
Oh OK, indeed.

Same problem here https://sciencepost.fr/le-monde-de-la-paleontologie-secoue-par-lannonce-de-la-decouverte-dadn-de-dinosaure/

**Comment by Shadok** [comment]
Indeed, they use window.Sddan instead of window.sddan.
Wouldn't it be possible to parse window keys to try a partial and case insensitive match on sddan* ?

**Comment by MathRobin** [comment]
Maybe. But it's too overkill. We should just check if sddan or Sddan is here and kick their ass depending on which one is present

**Comment by Shadok** [comment]
Another idea for custom implementation, if it would be possible to have a settings area where we can define custom js element (e.g. sddanJS) and associate it to a platform and maybe an url so custom elements don't have to be tested on each website.

It would be like this for clubic :
sddanJS / Sirdata / www.clubic.com (or *.clubic.com maybe)

**Comment by MathRobin** [comment]
Ok, problem found, it's not from misusage of case sddan vs Sddan, it's because Sirdata published a new version and generated class names used by my script has changed. Have a look to those lines :

https://github.com/MathRobin/Never-Consent/blob/8697cbebc2b702745d1210f4d1d46d7e173eec6e/src/nc.js#L91-L99

Not really the prettiest way... but there is still no known public API (if I'm not wrong, so I have to emulate user interaction.

Problem fixed in version 1.5.2, will be soon available publicly. Actueally in review process for all supported browsers

**Comment by MathRobin** [comment]
Fixed with https://github.com/MathRobin/Never-Consent/commit/83247437d931a76b19f4f733c0a700f1358e6a50
