### ISSUE TITLE
TrustArc/TrustE broken

### ISSUE THREAD

**Issue by herrernst** [MathRobin/Never-Consent#40]
Hi, on this site: https://wikitravel.org/de/Nationalpark_Donauauen the dialog doesn't disappear, but also the buttons do not work, so site is unusable. Current version in Chrome. Thanks.

**Comment by MathRobin** [comment]
Hi, thank you for your bug report. Sadly, the extension not yet support TrustE/TrustArc, but I can reproduce the bug easily. I tried to found if the bug is caused by the extension but it seems not.
So i think its trustArc which is crashed.
The good point of this is that i have an entrypoint now to know how to kick them

**Comment by MathRobin** [comment]
More info, maybe it's crashed because wikitravel doesn't implement correctly trustE
![Capture du 2020-09-01 15-30-22](https://user-images.githubusercontent.com/1046585/91857386-21708e80-ec68-11ea-878b-bab4faed1f9f.png)

**Comment by herrernst** [comment]
Thanks!
