### ISSUE TITLE
Manage ZIFF DAVIS

### ISSUE THREAD

**Issue by TontonSancho** [MathRobin/Never-Consent#41]
Example seen on : https://downdetector.fr/statut/github/

**Comment by MathRobin** [comment]
Interesting. If you want to open a PR, you're welcome. I hope I will have time soon to be able to investigate. Thanks for having reported it!

**Comment by TontonSancho** [comment]
Work in progress

**Comment by TontonSancho** [comment]
Good news, this one is 'evidon' based.
Maybe it will be 'generalizable' to all evidon derivative cookie collectors.

**Comment by MathRobin** [comment]
Yes some methods can be factorized. It's hard to identify each process. This extension is clearly not the best way to solve this global problem. At least, I hope a day, all sites will respect the law and the "do not track" browser flag.. . (ah ah)

**Comment by MathRobin** [comment]
There are at least three kinds of evidon : preferencesDialog, banner and barrier, maybe I have an idea. WIll try soon

**Comment by MathRobin** [comment]
Partially managed here. https://github.com/MathRobin/Never-Consent/commit/4a9a698140fb91f3bf7d1c72cfc662175fce9921

Sadly, Evidon barrier open an iframe in a modal. I can't access to it due to browser security restrictions (cross origin), for the moment, the only thing I can do is opening the right modal for user to allow it clicking by itself on the "reject all". I can't do more yet.

Maybe in a future version we can imagine to open the iframe url in another browser tab, click on the button, close the tab, refresh the page but I'm sceptical, i think it's a bit to intrusive. Maybe... Don't know
