### ISSUE TITLE
Manage these please?

### ISSUE THREAD

**Issue by beng7** [MathRobin/Never-Consent#49]
Hi
Can you please confirm Never-Consent also blocks these else make it block them:

Google Analytics
Facebook Pixel
Google Tag Manager
Hotjar Analytics
Google Publisher Tag
Youtube Embed
Vimeo Embed
Google Maps
AddThis Widget
ShareThis widget
Twitter Widget
SoundCloud Embed
SlideShare Embed
LinkedIn Widget
Instagram Embed
Pinterest Widget

Thanks

**Comment by MathRobin** [comment]
I thing the goal of this extension is not well understood. Never Consent is only designed to answer by negative to rgpd banner. Not to block trackers, cookies, etc. Mostly because uBlock, adblock & co does it very well.That's why in the readme I advise to install one of these in addition of never consent.
Never-Consent is based on the naive promise that websites will respect your choice on their rgpd banner/popup/whatever (and the law). For those who don't, and it's the majority, extensions like uBlock and adblock will be much better efficients.
