### ISSUE TITLE
Infinite Loading Loop on www.pharmazeutische-zeitung.de

### ISSUE THREAD

**Issue by nudgegoonies** [MathRobin/Never-Consent#78]
Loading of this page results in an infinite loading loop: https://www.pharmazeutische-zeitung.de

I suggest adding a button to temporary disable Never-Consent for such sites.

**Comment by MathRobin** [comment]
Hi,

Yeah it can happens, i marked it as a bug because it is.
Will have a look soon I hope.

Concerning your excellent feature request, it's already on roadmap for V2, have a look here if you want some updates: https://github.com/MathRobin/Never-Consent/issues/68
(when will have time, don't know when)

Many thanks for your bug report !

**Comment by nudgegoonies** [comment]
Thank you very much!

**Comment by MathRobin** [comment]
This bug reveals me something completely crazy. This website uses 2 differents platforms at the same time... WTF. Still searching for a solution.

**Comment by MathRobin** [comment]
Fixed, waiting for deployment from Mozilla & Google. Again, many thanks for your bug report !

**Comment by MathRobin** [comment]
Now available on any chromium-like browsers and Firefox of course !

**Comment by nudgegoonies** [comment]
Works - thanks a lot!
