### ISSUE TITLE
Cookie dialog on howlongtobeat

### ISSUE THREAD

**Issue by amo13** [MathRobin/Never-Consent#88]
https://howlongtobeat.com/

**Comment by MathRobin** [comment]
It depends on Ziff Davies platform, on which i already been stucked... (see here https://github.com/MathRobin/Never-Consent/issues/41) If you have any idea on how to... i'm still stucked sadly

Many thanks for having report this not-managed platform !

**Comment by amo13** [comment]
> If you have any idea on how to...

I probably won't solve this, but I'd be eager to try if you can drop me a few hints. 
What is the easiest way to go about trying? Pasting the content of nc.js into the web console of my firefox and then doing some trial and error? What are normally the first things to try?

Thanks for putting it all together into this extension by the way!

**Comment by MathRobin** [comment]
Your questions are really useful, I realise that I never pusblished an how-to for contribution... Will add it asap

Actually I develop mostly on Chrome, i just go on private mode, and try with console log and copy pasting script. 

Firstly I try to search for a JS API, which seems to be the more stable in time, after i search to solve the problem using dom, but as a log of platforms uses webpack build with random hash for classnames, it's not really the best way. I try to don't rely on text search, because of internationalization problems and not really a stable method too of course...

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
